{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airia-test-pod.serviceAccountName" . }}
  namespace: {{ include "airia-test-pod.namespace" . }}
  labels:
    {{- include "airia-test-pod.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}