apiVersion: v1
kind: ConfigMap
metadata:
  name: airia-test-pod-config
  namespace: airia-preprod
data:
  # PostgreSQL configuration
  postgres-host: "your-postgres-server.postgres.database.azure.com"
  postgres-port: "5432"
  postgres-database: "postgres"
  postgres-sslmode: "require"
  
  # Azure Blob Storage configuration
  blob-account-name: "yourstorageaccount"
  blob-container-name: "test-container"
  
  # Azure OpenAI configuration
  azure-openai-endpoint: "https://your-openai.openai.azure.com/"
  azure-openai-deployment-name: "gpt-35-turbo"
  
  # Azure Document Intelligence configuration
  azure-doc-intel-endpoint: "https://your-doc-intel.cognitiveservices.azure.com/"
  azure-doc-intel-model: "prebuilt-document"
  
  # SSL certificate testing URLs (comma-separated)
  ssl-test-urls: "https://api.example.com,https://app.example.com"
  
  # Kubernetes configuration
  storage-class: "default"
  test-pvc-size: "1Gi"