apiVersion: apps/v1
kind: Deployment
metadata:
  name: airia-test-pod
  labels:
    app: airia-test-pod
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airia-test-pod
  template:
    metadata:
      labels:
        app: airia-test-pod
        version: v1
    spec:
      containers:
      - name: airia-test-pod
        image: ghcr.io/davidpacold/airia-test-pod:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: airia-test-pod-secrets
              key: auth_username
        - name: AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airia-test-pod-secrets
              key: auth_password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: airia-test-pod-secrets
              key: secret_key
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: airia-test-pod-config
              key: postgres_host
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: airia-test-pod-config
              key: postgres_database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: airia-test-pod-secrets
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airia-test-pod-secrets
              key: postgres_password
        
        # Comprehensive health checks for Kubernetes
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        
        startupProbe:
          httpGet:
            path: /health/live
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 12  # Allow up to 60 seconds for startup
        
        # Resource limits for better scheduling
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        
      # Pod security context
      securityContext:
        fsGroup: 1000
      
      # Service account
      serviceAccountName: airia-test-pod
      
      # Image pull policy
      imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: airia-test-pod-service
  labels:
    app: airia-test-pod
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: airia-test-pod

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airia-test-pod
  labels:
    app: airia-test-pod

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airia-test-pod-config
  labels:
    app: airia-test-pod
data:
  postgres_host: "postgres.default.svc.cluster.local"
  postgres_database: "airia_test"
  postgres_port: "5432"
  postgres_sslmode: "require"

---
apiVersion: v1
kind: Secret
metadata:
  name: airia-test-pod-secrets
  labels:
    app: airia-test-pod
type: Opaque
stringData:
  auth_username: "admin"
  auth_password: "change-this-password"
  secret_key: "change-this-secret-key-in-production"
  postgres_user: "airia_user"
  postgres_password: "change-this-password"