apiVersion: v1
kind: Secret
metadata:
  name: airia-test-pod-postgres
  namespace: airia-preprod
type: Opaque
data:
  # PostgreSQL credentials - CHANGE THESE!
  # username: postgres (base64 encoded)
  username: cG9zdGdyZXM=
  # password: your-password-here (base64 encoded)
  password: eW91ci1wYXNzd29yZC1oZXJl