name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.2)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Update all version references
      run: |
        # Determine version based on trigger type
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          # Manual release with specified version
          VERSION="${{ github.event.inputs.version }}"
        elif [ "${{ github.event_name }}" = "push" ]; then
          # Auto-release: find next available patch version
          # Fetch all tags first
          git fetch --tags
          
          # Get latest tag or use default
          LATEST_TAG=$(git tag -l "v*" | sort -V | tail -1)
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="v1.0.0"
            echo "No tags found, starting from v1.0.0"
          fi
          
          LATEST_VERSION=${LATEST_TAG#v}
          IFS='.' read -r major minor patch <<< "$LATEST_VERSION"
          
          # Ensure variables are set
          major=${major:-1}
          minor=${minor:-0}
          patch=${patch:-0}
          
          # Find next available version
          NEW_PATCH=$((patch + 1))
          while git rev-parse "v$major.$minor.$NEW_PATCH" >/dev/null 2>&1; do
            echo "Version v$major.$minor.$NEW_PATCH already exists, trying next..."
            NEW_PATCH=$((NEW_PATCH + 1))
          done
          
          VERSION="$major.$minor.$NEW_PATCH"
          echo "Auto-incrementing from $LATEST_VERSION to $VERSION"
        else
          # Release event
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
        fi
        
        # Update Chart.yaml version
        sed -i "s/^version:.*/version: $VERSION/" helm/airia-test-pod/Chart.yaml
        sed -i "s/^appVersion:.*/appVersion: \"$VERSION\"/" helm/airia-test-pod/Chart.yaml
        
        # Update application version references
        sed -i "s/version: str = \"[^\"]*\"/version: str = \"$VERSION\"/" app/config.py
        sed -i "s/app = FastAPI(title=\"Airia Infrastructure Test Pod\", version=\"[^\"]*\")/app = FastAPI(title=\"Airia Infrastructure Test Pod\", version=\"$VERSION\")/" app/main.py
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" app/main.py
        
        echo "Updated all version references to $VERSION"
        
        # Show what changed
        echo "Changes made:"
        git diff --no-index /dev/null helm/airia-test-pod/Chart.yaml | grep "^+" | grep -E "(version|appVersion)" || true
        git diff --no-index /dev/null app/config.py | grep "^+" | grep version || true
        git diff --no-index /dev/null app/main.py | grep "^+" | grep version || true

    # Docker image building is now handled by build-and-publish.yml workflow
    # This prevents duplicate Docker builds on the same push

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.14.0

    - name: Package Helm chart
      run: |
        helm package helm/airia-test-pod --destination ./helm-packages

    - name: Create Git Tag (for auto and manual releases)
      if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
      run: |
        # Extract version from previous step
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          # Get auto-generated version from earlier step
          LATEST_TAG=$(git tag -l "v*" | sort -V | tail -1 || echo "v1.0.0")
          LATEST_VERSION=${LATEST_TAG#v}
          IFS='.' read -r major minor patch <<< "$LATEST_VERSION"
          
          # Find next available version
          NEW_PATCH=$((patch + 1))
          while git rev-parse "v$major.$minor.$NEW_PATCH" >/dev/null 2>&1; do
            NEW_PATCH=$((NEW_PATCH + 1))
          done
          VERSION="$major.$minor.$NEW_PATCH"
        fi
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if tag already exists and skip if it does
        if git rev-parse "v$VERSION" >/dev/null 2>&1; then
          echo "Tag v$VERSION already exists, skipping tag creation"
        else
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"
        fi

    - name: Set version output
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" = "push" ]; then
          LATEST_TAG=$(git tag -l "v*" | sort -V | tail -1 || echo "v1.0.0")
          LATEST_VERSION=${LATEST_TAG#v}
          IFS='.' read -r major minor patch <<< "$LATEST_VERSION"
          
          # Find next available version
          NEW_PATCH=$((patch + 1))
          while git rev-parse "v$major.$minor.$NEW_PATCH" >/dev/null 2>&1; do
            NEW_PATCH=$((NEW_PATCH + 1))
          done
          echo "version=$major.$minor.$NEW_PATCH" >> $GITHUB_OUTPUT
        else
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
        fi

    - name: Upload Helm chart to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: v${{ steps.version.outputs.version }}
        files: ./helm-packages/*.tgz
        generate_release_notes: true

    - name: Setup Helm repository files
      if: success()
      run: |
        # Create docs directory for Helm repository
        mkdir -p docs
        cp ./helm-packages/*.tgz docs/
        
        # Generate index.yaml for Helm repository
        helm repo index docs --url https://davidpacold.github.io/airia-test-pod/
        
        # Configure git with [skip ci] to prevent infinite loops
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "Update Helm repository with v${{ steps.version.outputs.version }} [skip ci]" || exit 0
        git push origin main